# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.ssh.private_key_path = "../vagrant.id_rsa"

  config.vm.box = "cent6"
  config.vm.host_name = "cent6"
  config.vm.network :hostonly, "192.168.33.10"
  config.vm.customize ["modifyvm", :id,
    "--name", "cent6",
    "--memory", 512
  ]
end
